[providers]
node = true

[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn-1_x"]

[phases.install]
cmd = "yarn install --frozen-lockfile"

[phases.build]
cmd = "cd apps/api && yarn build"

[phases.start]
cmd = "cd apps/api && yarn start:prod"
