[providers]
node = true

[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn-1_x"]

[phases.install]
cmd = "yarn install --frozen-lockfile"

[phases.build]
cmd = "turbo run build --filter=@supaspend/api"

[phases.start]
cmd = "turbo run start:prod --filter=@supaspend/api"
