[build]
builder = "nixpacks"
buildCommand = "turbo run build --filter=@supaspend/api"

[deploy]
startCommand = "turbo run start:prod --filter=@supaspend/api"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "4444"
NODE_ENV = "production"
NODE_VERSION = "20"
NIXPACKS_NODE_VERSION = "20"
