[build]
builder = "nixpacks"
buildCommand = "cd apps/api && yarn build"

[deploy]
startCommand = "cd apps/api && yarn start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "4444"
NODE_ENV = "production"
NODE_VERSION = "20"
NIXPACKS_NODE_VERSION = "20"
